// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXYvYL3ntM3JqnIRtbRXjjviR_vTi7XY',
    appId: '1:418875428443:web:91bc6d28fdfb5b5953797e',
    messagingSenderId: '418875428443',
    projectId: 'dal-ai-agent-hackathon',
    authDomain: 'dal-ai-agent-hackathon.firebaseapp.com',
    storageBucket: 'dal-ai-agent-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1AVngUlxfMK85d8s7GokN0Y6oxvX_2y8',
    appId: '1:418875428443:android:120a22bf1d2ff88753797e',
    messagingSenderId: '418875428443',
    projectId: 'dal-ai-agent-hackathon',
    storageBucket: 'dal-ai-agent-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZstjGuz8cYmFo2SPSsFYy7CzSK_HHxeI',
    appId: '1:418875428443:ios:b180a7d4d4522b8453797e',
    messagingSenderId: '418875428443',
    projectId: 'dal-ai-agent-hackathon',
    storageBucket: 'dal-ai-agent-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZstjGuz8cYmFo2SPSsFYy7CzSK_HHxeI',
    appId: '1:418875428443:ios:b180a7d4d4522b8453797e',
    messagingSenderId: '418875428443',
    projectId: 'dal-ai-agent-hackathon',
    storageBucket: 'dal-ai-agent-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDXYvYL3ntM3JqnIRtbRXjjviR_vTi7XY',
    appId: '1:418875428443:web:a34d6e7ec3e01bbf53797e',
    messagingSenderId: '418875428443',
    projectId: 'dal-ai-agent-hackathon',
    authDomain: 'dal-ai-agent-hackathon.firebaseapp.com',
    storageBucket: 'dal-ai-agent-hackathon.firebasestorage.app',
  );
}
