name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest

    - name: Run linting
      run: |
        source .venv/bin/activate
        black --check .
        isort --check-only .
        flake8 .
        mypy .

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push container
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/meal-planner-api:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/meal-planner-api:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy meal-planner-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/meal-planner-api:${{ github.sha }} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated 